// <auto-generated />
using System;
using Billing.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Billing.Api.Infrastructure.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    partial class BillingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
            modelBuilder.HasSequence("invoice_number_seq");

            modelBuilder.Entity("Billing.Api.Domain.AiDraftRun", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<long>("DurationMilliseconds").HasColumnType("bigint");
                    b.Property<decimal>("EstimatedCostUsd").HasPrecision(18, 8).HasColumnType("numeric(18,8)");
                    b.Property<string>("FailureCode").HasMaxLength(64).HasColumnType("character varying(64)");
                    b.Property<int>("InputTokens").HasColumnType("integer");
                    b.Property<string>("Model").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<int>("OutputTokens").HasColumnType("integer");
                    b.Property<string>("PromptVersion").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<string>("Status").IsRequired().HasMaxLength(16).HasColumnType("character varying(16)");
                    b.Property<string>("ToolNames").IsRequired().HasColumnType("jsonb");
                    b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.HasKey("Id");
                    b.ToTable("ai_draft_runs", (string)null);
                });

            modelBuilder.Entity("Billing.Api.Domain.Invoice", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTimeOffset?>("ClosedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("ClosedBy").HasMaxLength(120).HasColumnType("character varying(120)");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("CreatedBy").IsRequired().ValueGeneratedOnAdd().HasMaxLength(120).HasColumnType("character varying(120)").HasDefaultValue("sistema");
                    b.Property<long>("Number").ValueGeneratedOnAdd().HasColumnType("bigint").HasDefaultValueSql("nextval('invoice_number_seq')");
                    b.Property<string>("Status").IsRequired().HasMaxLength(16).HasColumnType("character varying(16)");
                    b.Property<Guid>("Version").IsConcurrencyToken().HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("Number").IsUnique();
                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("Billing.Api.Domain.InvoiceImport", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("ContentHash").IsRequired().HasMaxLength(64).HasColumnType("character(64)").IsFixedLength();
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("CreatedBy").IsRequired().HasMaxLength(120).HasColumnType("character varying(120)");
                    b.Property<int>("CreatedInvoices").HasColumnType("integer");
                    b.Property<string>("FileName").IsRequired().HasMaxLength(260).HasColumnType("character varying(260)");
                    b.HasKey("Id");
                    b.HasIndex("ContentHash").IsUnique().HasDatabaseName("ux_invoice_imports_hash");
                    b.ToTable("invoice_imports", (string)null);
                });

            modelBuilder.Entity("Billing.Api.Domain.AppUser", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("DisplayName").IsRequired().HasMaxLength(120).HasColumnType("character varying(120)");
                    b.Property<string>("PasswordHash").IsRequired().HasMaxLength(300).HasColumnType("character varying(300)");
                    b.Property<string>("UserName").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
                    b.HasKey("Id");
                    b.HasIndex("UserName").IsUnique().HasDatabaseName("ux_users_username");
                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Billing.Api.Domain.UserSession", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<DateTimeOffset>("ExpiresAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("TokenHash").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
                    b.Property<Guid>("UserId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("TokenHash").IsUnique().HasDatabaseName("ux_user_sessions_token");
                    b.HasIndex("UserId");
                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("Billing.Api.Domain.InvoiceClosureAttempt", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("ErrorCode").HasMaxLength(64).HasColumnType("character varying(64)");
                    b.Property<string>("ErrorMessage").HasMaxLength(500).HasColumnType("character varying(500)");
                    b.Property<string>("IgnoredItemsJson").HasColumnType("jsonb");
                    b.Property<Guid>("InvoiceId").HasColumnType("uuid");
                    b.Property<DateTimeOffset>("NextRetryAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("PayloadHash").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
                    b.Property<int>("RetryCount").HasColumnType("integer");
                    b.Property<string>("State").IsRequired().HasMaxLength(16).HasColumnType("character varying(16)");
                    b.Property<DateTimeOffset>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.Property<Guid>("Version").IsConcurrencyToken().HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("InvoiceId").IsUnique().HasFilter("\"State\" = 'Pending'");
                    b.HasIndex("State", "NextRetryAt");
                    b.ToTable("invoice_closure_attempts", (string)null);
                });

            modelBuilder.Entity("Billing.Api.Domain.InvoiceItem", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<Guid>("InvoiceId").HasColumnType("uuid");
                    b.Property<string>("ProductCode").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
                    b.Property<string>("ProductDescription").IsRequired().HasMaxLength(300).HasColumnType("character varying(300)");
                    b.Property<Guid>("ProductId").HasColumnType("uuid");
                    b.Property<int>("Quantity").HasColumnType("integer");
                    b.HasKey("Id");
                    b.HasIndex("InvoiceId", "ProductId").IsUnique();
                    b.ToTable("invoice_items", null, t => t.HasCheckConstraint("ck_invoice_items_quantity", "\"Quantity\" > 0"));
                });

            modelBuilder.Entity("Billing.Api.Domain.InvoiceClosureAttempt", b =>
                {
                    b.HasOne("Billing.Api.Domain.Invoice", null)
                        .WithMany("ClosureAttempts")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Billing.Api.Domain.InvoiceItem", b =>
                {
                    b.HasOne("Billing.Api.Domain.Invoice", null)
                        .WithMany("Items")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Billing.Api.Domain.UserSession", b =>
                {
                    b.HasOne("Billing.Api.Domain.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("User");
                });

            modelBuilder.Entity("Billing.Api.Domain.Invoice", b =>
                {
                    b.Navigation("ClosureAttempts");
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
