// <auto-generated />
using Inventory.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Inventory.Api.Infrastructure.Migrations;

[DbContext(typeof(InventoryDbContext))]
internal sealed class InventoryDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Inventory.Api.Domain.Product", entity =>
        {
            entity.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            entity.Property<int>("Balance").HasColumnType("integer");
            entity.Property<string>("Code").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
            entity.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
            entity.Property<string>("Description").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
            entity.Property<bool>("TracksStock").ValueGeneratedOnAdd().HasColumnType("boolean").HasDefaultValue(true);
            entity.HasKey("Id");
            entity.HasIndex("Code").IsUnique().HasDatabaseName("UX_Products_Code");
            entity.ToTable("Products", null, table =>
                table.HasCheckConstraint("CK_Products_Balance", "\"Balance\" >= 0"));
        });

        modelBuilder.Entity("Inventory.Api.Domain.StockDebitOperation", entity =>
        {
            entity.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            entity.Property<Guid>("AttemptId").HasColumnType("uuid");
            entity.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
            entity.Property<string>("ErrorCode").HasMaxLength(64).HasColumnType("character varying(64)");
            entity.Property<string>("ErrorMessage").HasMaxLength(500).HasColumnType("character varying(500)");
            entity.Property<string>("IgnoredItemsJson").HasColumnType("jsonb");
            entity.Property<DateTimeOffset?>("FinishedAt").HasColumnType("timestamp with time zone");
            entity.Property<Guid>("InvoiceId").HasColumnType("uuid");
            entity.Property<string>("RequestHash").IsRequired().HasMaxLength(64).HasColumnType("character(64)").IsFixedLength();
            entity.Property<string>("State").IsRequired().HasMaxLength(16).HasColumnType("character varying(16)");
            entity.HasKey("Id");
            entity.HasIndex("AttemptId").IsUnique().HasDatabaseName("UX_StockDebitOperations_AttemptId");
            entity.ToTable("StockDebitOperations", (string)null);
        });

        modelBuilder.Entity("Inventory.Api.Domain.StockMovement", entity =>
        {
            entity.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            entity.Property<int>("BalanceAfter").HasColumnType("integer");
            entity.Property<int>("BalanceBefore").HasColumnType("integer");
            entity.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
            entity.Property<Guid>("OperationId").HasColumnType("uuid");
            entity.Property<Guid>("ProductId").HasColumnType("uuid");
            entity.Property<int>("Quantity").HasColumnType("integer");
            entity.HasKey("Id");
            entity.HasIndex("OperationId");
            entity.HasIndex("ProductId");
            entity.ToTable("StockMovements", null, table =>
            {
                table.HasCheckConstraint(
                    "CK_StockMovements_Balances",
                    "\"BalanceBefore\" >= 0 AND \"BalanceAfter\" >= 0 AND \"BalanceAfter\" = \"BalanceBefore\" - \"Quantity\"");
                table.HasCheckConstraint("CK_StockMovements_Quantity", "\"Quantity\" > 0");
            });
        });

        modelBuilder.Entity("Inventory.Api.Domain.StockMovement", entity =>
        {
            entity.HasOne("Inventory.Api.Domain.StockDebitOperation", "Operation")
                .WithMany("Movements")
                .HasForeignKey("OperationId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            entity.HasOne("Inventory.Api.Domain.Product", "Product")
                .WithMany()
                .HasForeignKey("ProductId")
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired();
            entity.Navigation("Operation");
            entity.Navigation("Product");
        });

        modelBuilder.Entity("Inventory.Api.Domain.StockDebitOperation", entity =>
            entity.Navigation("Movements"));
#pragma warning restore 612, 618
    }
}
